// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoaBZc3cIWo3R36nhsXctGaR_MBAcPj4w',
    appId: '1:242258118419:web:84106682ab69038639fce6',
    messagingSenderId: '242258118419',
    projectId: 'vroo-demo',
    authDomain: 'vroo-demo.firebaseapp.com',
    storageBucket: 'vroo-demo.firebasestorage.app',
    measurementId: 'G-EW81WW70EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8pFvOm-iKW8ZqwfqBw8Hd5aOFnjpml_Q',
    appId: '1:242258118419:android:f645180767c1a75339fce6',
    messagingSenderId: '242258118419',
    projectId: 'vroo-demo',
    storageBucket: 'vroo-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_RdA9O01e0sBZtVWoYQVG4rkuCezC9zc',
    appId: '1:242258118419:ios:94d2d5a59dda225539fce6',
    messagingSenderId: '242258118419',
    projectId: 'vroo-demo',
    storageBucket: 'vroo-demo.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_RdA9O01e0sBZtVWoYQVG4rkuCezC9zc',
    appId: '1:242258118419:ios:94d2d5a59dda225539fce6',
    messagingSenderId: '242258118419',
    projectId: 'vroo-demo',
    storageBucket: 'vroo-demo.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoaBZc3cIWo3R36nhsXctGaR_MBAcPj4w',
    appId: '1:242258118419:web:85e8cb6c296ec60439fce6',
    messagingSenderId: '242258118419',
    projectId: 'vroo-demo',
    authDomain: 'vroo-demo.firebaseapp.com',
    storageBucket: 'vroo-demo.firebasestorage.app',
    measurementId: 'G-8MMB64Y0JR',
  );
}
