// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7gpsj-TGGXfpwU2kwDH6gwHB_MhhfHF4',
    appId: '1:167670342099:web:9445d0599a1e997bec4f26',
    messagingSenderId: '167670342099',
    projectId: 'vroo-2c1a3',
    authDomain: 'vroo-2c1a3.firebaseapp.com',
    storageBucket: 'vroo-2c1a3.firebasestorage.app',
    measurementId: 'G-PS7PC2MF5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYN2QVcsMxl9XodAlzeblKDc5BwYSIh4o',
    appId: '1:167670342099:android:1969fdf9cb625866ec4f26',
    messagingSenderId: '167670342099',
    projectId: 'vroo-2c1a3',
    storageBucket: 'vroo-2c1a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7YuL9byGarDo2GgVgKqkZDg9TLpk6l4Q',
    appId: '1:167670342099:ios:1cee7d690957dafbec4f26',
    messagingSenderId: '167670342099',
    projectId: 'vroo-2c1a3',
    storageBucket: 'vroo-2c1a3.firebasestorage.app',
    iosBundleId: 'com.example.vrooTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7YuL9byGarDo2GgVgKqkZDg9TLpk6l4Q',
    appId: '1:167670342099:ios:1cee7d690957dafbec4f26',
    messagingSenderId: '167670342099',
    projectId: 'vroo-2c1a3',
    storageBucket: 'vroo-2c1a3.firebasestorage.app',
    iosBundleId: 'com.example.vrooTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7gpsj-TGGXfpwU2kwDH6gwHB_MhhfHF4',
    appId: '1:167670342099:web:2b62c74e03abaa17ec4f26',
    messagingSenderId: '167670342099',
    projectId: 'vroo-2c1a3',
    authDomain: 'vroo-2c1a3.firebaseapp.com',
    storageBucket: 'vroo-2c1a3.firebasestorage.app',
    measurementId: 'G-XLQMQZSYXJ',
  );
}
